In [84]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
import os

- In city_listings folder, takes all the csv files turns them into dataframes appends them into a dataframe list 
- We row append all the dataframes in the dataframe list
- We upload the dataframe in a csv file

In [85]:
folder_path = 'city_listings'

dataframes = []
for item in os.listdir(folder_path):
    item_path = os.path.join(folder_path, item)
    if os.path.isfile(item_path):
        df = pd.read_csv(item_path)
        dataframes.append(df)

complete = pd.concat(dataframes, ignore_index=True)

complete.to_csv('./American_house_prices_dataset.csv')

complete

,Unnamed: 0,zpid,rawHomeStatusCd,marketingStatusSimplifiedCd,imgSrc,hasImage,detailUrl,statusType,statusText,price,...,info2String,badgeInfo.type,badgeInfo.text,hdpData.homeInfo.listing_sub_type.is_forAuction,isR4R,hdpData.homeInfo.rentalMarketingSubType,communityName,isCdpResult,isComingSoonCommunity,style
0,0,59141778.0,Pending,Non Owner Occupied,https://photos.zillowstatic.com/fp/8e78d9c3127...,True,/homedetails/9-Robken-Rd-Roslindale-MA-02131/5...,SOLD,Sold,"$819,500",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,59172422.0,RecentlySold,RecentChange,https://photos.zillowstatic.com/fp/17fa75ec2c3...,True,/homedetails/130-Appleton-St-APT-2A-Boston-MA-...,SOLD,Sold,"$880,000",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,NaN,NaN,NaN,https://photos.zillowstatic.com/fp/db4bb4b2af8...,True,/b/70-leo-m-birmingham-pkwy-brighton-ma-5j3ZG6/,SOLD,For Rent,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,59109603.0,RecentlySold,RecentChange,https://photos.zillowstatic.com/fp/72bb4e8b21a...,True,/homedetails/64-Bakersfield-St-Dorchester-MA-0...,SOLD,Sold,$1.25M,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,59110140.0,RecentlySold,RecentChange,https://photos.zillowstatic.com/fp/831ef787fbd...,True,/homedetails/123-Norwell-St-Dorchester-MA-0212...,SOLD,Sold,"$805,000",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7498,496,489212.0,RecentlySold,RecentChange,https://photos.zillowstatic.com/fp/e737d276b55...,True,/homedetails/5108-N-Capitol-St-NW-Washington-D...,SOLD,Sold,"$465,000",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7499,497,496388.0,RecentlySold,RecentChange,https://photos.zillowstatic.com/fp/21bb2c27339...,True,/homedetails/3110-10th-St-NE-Washington-DC-200...,SOLD,Sold,$1.02M,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7500,498,508533.0,RecentlySold,Non Owner Occupied,https://maps.googleapis.com/maps/api/staticmap...,NaN,/homedetails/331-16th-St-NE-Washington-DC-2000...,SOLD,Sold,"$550,000",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7501,499,513167.0,RecentlySold,RecentChange,https://photos.zillowstatic.com/fp/5e8a4c011dd...,True,/homedetails/5218-Hayes-St-NE-Washington-DC-20...,SOLD,Sold,"$370,000",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7502,500,NaN,NaN,NaN,https://photos.zillowstatic.com/fp/a4e773c5431...,True,/community/brookland-grove/29726777_plid/,FOR_SALE,NaN,"From $859,900",...,NaN,NaN,NaN,NaN,NaN,NaN,Brookland Grove,True,False,Urban

Imported our new combined dataframe

In [86]:
df=pd.read_csv(r'American_house_prices_dataset.csv')
df

,Unnamed: 0.1,Unnamed: 0,zpid,rawHomeStatusCd,marketingStatusSimplifiedCd,imgSrc,hasImage,detailUrl,statusType,statusText,...,info2String,badgeInfo.type,badgeInfo.text,hdpData.homeInfo.listing_sub_type.is_forAuction,isR4R,hdpData.homeInfo.rentalMarketingSubType,communityName,isCdpResult,isComingSoonCommunity,style
0,0,0,59141778.0,Pending,Non Owner Occupied,https://photos.zillowstatic.com/fp/8e78d9c3127...,True,/homedetails/9-Robken-Rd-Roslindale-MA-02131/5...,SOLD,Sold,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1,59172422.0,RecentlySold,RecentChange,https://photos.zillowstatic.com/fp/17fa75ec2c3...,True,/homedetails/130-Appleton-St-APT-2A-Boston-MA-...,SOLD,Sold,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,2,NaN,NaN,NaN,https://photos.zillowstatic.com/fp/db4bb4b2af8...,True,/b/70-leo-m-birmingham-pkwy-brighton-ma-5j3ZG6/,SOLD,For Rent,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,3,59109603.0,RecentlySold,RecentChange,https://photos.zillowstatic.com/fp/72bb4e8b21a...,True,/homedetails/64-Bakersfield-St-Dorchester-MA-0...,SOLD,Sold,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,4,59110140.0,RecentlySold,RecentChange,https://photos.zillowstatic.com/fp/831ef787fbd...,True,/homedetails/123-Norwell-St-Dorchester-MA-0212...,SOLD,Sold,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7498,7498,496,489212.0,RecentlySold,RecentChange,https://photos.zillowstatic.com/fp/e737d276b55...,True,/homedetails/5108-N-Capitol-St-NW-Washington-D...,SOLD,Sold,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7499,7499,497,496388.0,RecentlySold,RecentChange,https://photos.zillowstatic.com/fp/21bb2c27339...,True,/homedetails/3110-10th-St-NE-Washington-DC-200...,SOLD,Sold,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7500,7500,498,508533.0,RecentlySold,Non Owner Occupied,https://maps.googleapis.com/maps/api/staticmap...,NaN,/homedetails/331-16th-St-NE-Washington-DC-2000...,SOLD,Sold,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7501,7501,499,513167.0,RecentlySold,RecentChange,https://photos.zillowstatic.com/fp/5e8a4c011dd...,True,/homedetails/5218-Hayes-St-NE-Washington-DC-20...,SOLD,Sold,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7502,7502,500,NaN,NaN,NaN,https://photos.zillowstatic.com/fp/a4e773c5431...,True,/community/brookland-grove/29726777_plid/,FOR_SALE,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Brookland Grove,True,False,Urban

- We find the missing value % in all columns of a dataframe.
- We delete the columns that have more than 20% missing values.
- Columns with a large proportion of missing values may indicate poor data quality or inconsistency.

In [87]:
missingPerc=df.isnull().sum()/df.shape[0]
missingPerc

Unnamed: 0.1                               0.000000
Unnamed: 0                                 0.000000
zpid                                       0.172864
rawHomeStatusCd                            0.172864
marketingStatusSimplifiedCd                0.172864
                                             ...
hdpData.homeInfo.rentalMarketingSubType    0.999467
communityName                              0.999467
isCdpResult                                0.999467
isComingSoonCommunity                      0.999467
style                                      0.999733
Length: 111, dtype: float64

In [88]:
toomuchmissingCols=missingPerc[missingPerc>0.2].index
toomuchmissingCols

Index(['listingType', 'info6String', 'brokerName', 'timeOnZillow',
       'hdpData.homeInfo.zestimate',
       'hdpData.homeInfo.listing_sub_type.is_FSBA',
       'hdpData.homeInfo.timeOnZillow', 'hdpData.homeInfo.taxAssessedValue',
       'hdpData.homeInfo.lotAreaValue', 'hdpData.homeInfo.lotAreaUnit',
       'hdpData.homeInfo.unit', 'plid', 'minBeds', 'minBaths', 'minArea',
       'lotId', 'buildingId', 'isBuilding', 'canSaveBuilding', 'unitCount',
       'hdpData.homeInfo.datePriceChanged', 'hdpData.homeInfo.priceReduction',
       'hdpData.homeInfo.priceChange', 'buildingName',
       'hdpData.homeInfo.isRentalWithBasePrice', 'availabilityDate',
       'hdpData.homeInfo.listing_sub_type.is_FSBO', 'streetViewURL',
       'streetViewMetadataURL', 'lotAreaString', 'info3String',
       'hdpData.homeInfo.videoCount', 'info1String', 'builderName',
       'hdpData.homeInfo.listing_sub_type.is_newHome',
       'hdpData.homeInfo.providerListingID',
       'hdpData.homeInfo.newConstructionType',
       'hdpData.homeInfo.listing_sub_type.is_openHouse',
       'hdpData.homeInfo.openHouse',
       'hdpData.homeInfo.open_house_info.open_house_showing', 'info2String',
       'badgeInfo.type', 'badgeInfo.text',
       'hdpData.homeInfo.listing_sub_type.is_forAuction', 'isR4R',
       'hdpData.homeInfo.rentalMarketingSubType', 'communityName',
       'isCdpResult', 'isComingSoonCommunity', 'style'],
      dtype='object')

In [89]:
df.drop(columns=toomuchmissingCols,inplace=True)

In [90]:
df

,Unnamed: 0.1,Unnamed: 0,zpid,rawHomeStatusCd,marketingStatusSimplifiedCd,imgSrc,hasImage,detailUrl,statusType,statusText,...,hdpData.homeInfo.isUnmappable,hdpData.homeInfo.isPreforeclosureAuction,hdpData.homeInfo.priceForHDP,hdpData.homeInfo.isNonOwnerOccupied,hdpData.homeInfo.isPremierBuilder,hdpData.homeInfo.isZillowOwned,hdpData.homeInfo.currency,hdpData.homeInfo.country,hdpData.homeInfo.isShowcaseListing,hdpData.homeInfo.homeStatusForHDP
0,0,0,59141778.0,Pending,Non Owner Occupied,https://photos.zillowstatic.com/fp/8e78d9c3127...,True,/homedetails/9-Robken-Rd-Roslindale-MA-02131/5...,SOLD,Sold,...,False,False,819500.0,True,False,False,USD,USA,False,NaN
1,1,1,59172422.0,RecentlySold,RecentChange,https://photos.zillowstatic.com/fp/17fa75ec2c3...,True,/homedetails/130-Appleton-St-APT-2A-Boston-MA-...,SOLD,Sold,...,False,False,880000.0,True,False,False,USD,USA,False,RECENTLY_SOLD
2,2,2,NaN,NaN,NaN,https://photos.zillowstatic.com/fp/db4bb4b2af8...,True,/b/70-leo-m-birmingham-pkwy-brighton-ma-5j3ZG6/,SOLD,For Rent,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,3,59109603.0,RecentlySold,RecentChange,https://photos.zillowstatic.com/fp/72bb4e8b21a...,True,/homedetails/64-Bakersfield-St-Dorchester-MA-0...,SOLD,Sold,...,False,False,1250000.0,True,False,False,USD,USA,False,RECENTLY_SOLD
4,4,4,59110140.0,RecentlySold,RecentChange,https://photos.zillowstatic.com/fp/831ef787fbd...,True,/homedetails/123-Norwell-St-Dorchester-MA-0212...,SOLD,Sold,...,False,False,805000.0,True,False,False,USD,USA,False,RECENTLY_SOLD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7498,7498,496,489212.0,RecentlySold,RecentChange,https://photos.zillowstatic.com/fp/e737d276b55...,True,/homedetails/5108-N-Capitol-St-NW-Washington-D...,SOLD,Sold,...,False,False,465000.0,True,False,False,USD,USA,False,RECENTLY_SOLD
7499,7499,497,496388.0,RecentlySold,RecentChange,https://photos.zillowstatic.com/fp/21bb2c27339...,True,/homedetails/3110-10th-St-NE-Washington-DC-200...,SOLD,Sold,...,False,False,1020000.0,True,False,False,USD,USA,False,RECENTLY_SOLD
7500,7500,498,508533.0,RecentlySold,Non Owner Occupied,https://maps.googleapis.com/maps/api/staticmap...,NaN,/homedetails/331-16th-St-NE-Washington-DC-2000...,SOLD,Sold,...,False,False,550000.0,True,False,False,USD,USA,False,RECENTLY_SOLD
7501,7501,499,513167.0,RecentlySold,RecentChange,https://photos.zillowstatic.com/fp/5e8a4c011dd...,True,/homedetails/5218-Hayes-St-NE-Washington-DC-20...,SOLD,Sold,...,False,False,370000.0,True,False,False,USD,USA,False,RECENTLY_SOLD
7502,7502,500,NaN,NaN,NaN,https://photos.zillowstatic.com/fp/a4e773c5431...,True,/community/brookland-grove/29726777_plid/,FOR_SALE,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

- There are 4 columns which all indicate price
- we will rename hdpData.homeInfo.price and drop the rest of the columns

In [91]:
priceColumns=[]
for col in df.columns:
    if "price" in col:
        priceColumns.append(col)
priceColumns

['price',
 'priceLabel',
 'hdpData.homeInfo.price',
 'hdpData.homeInfo.priceForHDP']

In [92]:
df[priceColumns]

,price,priceLabel,hdpData.homeInfo.price,hdpData.homeInfo.priceForHDP
0,"$819,500",$820K,819500.0,819500.0
1,"$880,000",$880K,880000.0,880000.0
2,NaN,NaN,NaN,NaN
3,$1.25M,$1.25M,1250000.0,1250000.0
4,"$805,000",$805K,805000.0,805000.0
...,...,...,...,...
7498,"$465,000",$465K,465000.0,465000.0
7499,$1.02M,$1.02M,1020000.0,1020000.0
7500,"$550,000",$550K,550000.0,550000.0
7501,"$370,000",$370K,370000.0,370000.0
7502,"From $859,900",NaN,NaN,NaN

In [93]:
df.drop(columns=["price","priceLabel","hdpData.homeInfo.priceForHDP"],inplace=True)
df.rename(columns={"hdpData.homeInfo.price":"price"},inplace=True)

In [94]:
df

,Unnamed: 0.1,Unnamed: 0,zpid,rawHomeStatusCd,marketingStatusSimplifiedCd,imgSrc,hasImage,detailUrl,statusType,statusText,...,hdpData.homeInfo.rentZestimate,hdpData.homeInfo.isUnmappable,hdpData.homeInfo.isPreforeclosureAuction,hdpData.homeInfo.isNonOwnerOccupied,hdpData.homeInfo.isPremierBuilder,hdpData.homeInfo.isZillowOwned,hdpData.homeInfo.currency,hdpData.homeInfo.country,hdpData.homeInfo.isShowcaseListing,hdpData.homeInfo.homeStatusForHDP
0,0,0,59141778.0,Pending,Non Owner Occupied,https://photos.zillowstatic.com/fp/8e78d9c3127...,True,/homedetails/9-Robken-Rd-Roslindale-MA-02131/5...,SOLD,Sold,...,3999.0,False,False,True,False,False,USD,USA,False,NaN
1,1,1,59172422.0,RecentlySold,RecentChange,https://photos.zillowstatic.com/fp/17fa75ec2c3...,True,/homedetails/130-Appleton-St-APT-2A-Boston-MA-...,SOLD,Sold,...,3634.0,False,False,True,False,False,USD,USA,False,RECENTLY_SOLD
2,2,2,NaN,NaN,NaN,https://photos.zillowstatic.com/fp/db4bb4b2af8...,True,/b/70-leo-m-birmingham-pkwy-brighton-ma-5j3ZG6/,SOLD,For Rent,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,3,59109603.0,RecentlySold,RecentChange,https://photos.zillowstatic.com/fp/72bb4e8b21a...,True,/homedetails/64-Bakersfield-St-Dorchester-MA-0...,SOLD,Sold,...,6000.0,False,False,True,False,False,USD,USA,False,RECENTLY_SOLD
4,4,4,59110140.0,RecentlySold,RecentChange,https://photos.zillowstatic.com/fp/831ef787fbd...,True,/homedetails/123-Norwell-St-Dorchester-MA-0212...,SOLD,Sold,...,4964.0,False,False,True,False,False,USD,USA,False,RECENTLY_SOLD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7498,7498,496,489212.0,RecentlySold,RecentChange,https://photos.zillowstatic.com/fp/e737d276b55...,True,/homedetails/5108-N-Capitol-St-NW-Washington-D...,SOLD,Sold,...,3449.0,False,False,True,False,False,USD,USA,False,RECENTLY_SOLD
7499,7499,497,496388.0,RecentlySold,RecentChange,https://photos.zillowstatic.com/fp/21bb2c27339...,True,/homedetails/3110-10th-St-NE-Washington-DC-200...,SOLD,Sold,...,4749.0,False,False,True,False,False,USD,USA,False,RECENTLY_SOLD
7500,7500,498,508533.0,RecentlySold,Non Owner Occupied,https://maps.googleapis.com/maps/api/staticmap...,NaN,/homedetails/331-16th-St-NE-Washington-DC-2000...,SOLD,Sold,...,3994.0,False,False,True,False,False,USD,USA,False,RECENTLY_SOLD
7501,7501,499,513167.0,RecentlySold,RecentChange,https://photos.zillowstatic.com/fp/5e8a4c011dd...,True,/homedetails/5218-Hayes-St-NE-Washington-DC-20...,SOLD,Sold,...,2949.0,False,False,True,False,False,USD,USA,False,RECENTLY_SOLD
7502,7502,500,NaN,NaN,NaN,https://photos.zillowstatic.com/fp/a4e773c5431...,True,/community/brookland-grove/29726777_plid/,FOR_SALE,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Since price is our target feature, we have to delete rows that have price as null

In [95]:
nullPriceIndices=df["price"][df["price"].isnull()==True].index
df.drop(nullPriceIndices,inplace=True)
df.reset_index(inplace=True)

In [96]:
df

,index,Unnamed: 0.1,Unnamed: 0,zpid,rawHomeStatusCd,marketingStatusSimplifiedCd,imgSrc,hasImage,detailUrl,statusType,...,hdpData.homeInfo.rentZestimate,hdpData.homeInfo.isUnmappable,hdpData.homeInfo.isPreforeclosureAuction,hdpData.homeInfo.isNonOwnerOccupied,hdpData.homeInfo.isPremierBuilder,hdpData.homeInfo.isZillowOwned,hdpData.homeInfo.currency,hdpData.homeInfo.country,hdpData.homeInfo.isShowcaseListing,hdpData.homeInfo.homeStatusForHDP
0,0,0,0,59141778.0,Pending,Non Owner Occupied,https://photos.zillowstatic.com/fp/8e78d9c3127...,True,/homedetails/9-Robken-Rd-Roslindale-MA-02131/5...,SOLD,...,3999.0,False,False,True,False,False,USD,USA,False,NaN
1,1,1,1,59172422.0,RecentlySold,RecentChange,https://photos.zillowstatic.com/fp/17fa75ec2c3...,True,/homedetails/130-Appleton-St-APT-2A-Boston-MA-...,SOLD,...,3634.0,False,False,True,False,False,USD,USA,False,RECENTLY_SOLD
2,3,3,3,59109603.0,RecentlySold,RecentChange,https://photos.zillowstatic.com/fp/72bb4e8b21a...,True,/homedetails/64-Bakersfield-St-Dorchester-MA-0...,SOLD,...,6000.0,False,False,True,False,False,USD,USA,False,RECENTLY_SOLD
3,4,4,4,59110140.0,RecentlySold,RecentChange,https://photos.zillowstatic.com/fp/831ef787fbd...,True,/homedetails/123-Norwell-St-Dorchester-MA-0212...,SOLD,...,4964.0,False,False,True,False,False,USD,USA,False,RECENTLY_SOLD
4,5,5,5,59111749.0,RecentlySold,RecentChange,https://photos.zillowstatic.com/fp/d7cc4b52033...,True,/homedetails/8-Fowler-St-Dorchester-MA-02121/5...,SOLD,...,8970.0,False,False,True,False,False,USD,USA,False,RECENTLY_SOLD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6201,7497,7497,495,486407.0,RecentlySold,RecentChange,https://photos.zillowstatic.com/fp/5ff72887932...,True,/homedetails/308-Quackenbos-St-NW-Washington-D...,SOLD,...,4999.0,False,False,True,False,False,USD,USA,False,RECENTLY_SOLD
6202,7498,7498,496,489212.0,RecentlySold,RecentChange,https://photos.zillowstatic.com/fp/e737d276b55...,True,/homedetails/5108-N-Capitol-St-NW-Washington-D...,SOLD,...,3449.0,False,False,True,False,False,USD,USA,False,RECENTLY_SOLD
6203,7499,7499,497,496388.0,RecentlySold,RecentChange,https://photos.zillowstatic.com/fp/21bb2c27339...,True,/homedetails/3110-10th-St-NE-Washington-DC-200...,SOLD,...,4749.0,False,False,True,False,False,USD,USA,False,RECENTLY_SOLD
6204,7500,7500,498,508533.0,RecentlySold,Non Owner Occupied,https://maps.googleapis.com/maps/api/staticmap...,NaN,/homedetails/331-16th-St-NE-Washington-DC-2000...,SOLD,...,3994.0,False,False,True,False,False,USD,USA,False,RECENTLY_SOLD
6205,7501,7501,499,513167.0,RecentlySold,RecentChange,https://photos.zillowstatic.com/fp/5e8a4c011dd...,True,/homedetails/5218-Hayes-St-NE-Washington-DC-20...,SOLD,...,2949.0,False,False,True,False,False,USD,USA,False,RECENTLY_SOLD

Features that have a category which is more than 97.5% proportion have been deleted as they are not useful

In [97]:
tooMuch1Category=[]
for col in df.columns:
    maxVal=df[col].value_counts().sort_values(ascending=False).index[0]

    maxValProportion=df[col][df[col]==maxVal].shape[0]/df[col].shape[0]
    if maxValProportion>0.975:
        print(col,maxVal,maxValProportion*100)
        tooMuch1Category.append(col)

rawHomeStatusCd RecentlySold 99.70995810505961
statusType SOLD 100.0
isUserClaimingOwner False 100.0
isUserConfirmedClaim False 100.0
pgapt RecentlySold 99.70995810505961
shouldShowZestimateAsPrice False 99.9838865613922
hasVideo False 98.69481147276828
isHomeRec False 100.0
isFeaturedListing False 99.64550435062843
isShowcaseListing False 100.0
isFavorite False 100.0
visited False 100.0
variableData.type RECENTLY_SOLD 98.66258459555269
hdpData.homeInfo.homeStatus RECENTLY_SOLD 99.70995810505961
hdpData.homeInfo.daysOnZillow -1.0 100.0
hdpData.homeInfo.isFeatured False 99.64550435062843
hdpData.homeInfo.shouldHighlight False 100.0
hdpData.homeInfo.isUnmappable False 100.0
hdpData.homeInfo.isPreforeclosureAuction False 100.0
hdpData.homeInfo.isNonOwnerOccupied True 100.0
hdpData.homeInfo.isPremierBuilder False 99.90331936835321
hdpData.homeInfo.isZillowOwned False 100.0
hdpData.homeInfo.currency USD 100.0
hdpData.homeInfo.country USA 100.0
hdpData.homeInfo.isShowcaseListing False 100.0
hdpData.homeInfo.homeStatusForHDP RECENTLY_SOLD 97.82468578794715

In [98]:
print(f"We have {len(tooMuch1Category)} such columns")

We have 26 such columns

In [99]:
df.drop(columns=tooMuch1Category,inplace=True)
df

,index,Unnamed: 0.1,Unnamed: 0,zpid,marketingStatusSimplifiedCd,imgSrc,hasImage,detailUrl,statusText,address,...,hdpData.homeInfo.state,hdpData.homeInfo.latitude,hdpData.homeInfo.longitude,price,hdpData.homeInfo.dateSold,hdpData.homeInfo.bathrooms,hdpData.homeInfo.bedrooms,hdpData.homeInfo.livingArea,hdpData.homeInfo.homeType,hdpData.homeInfo.rentZestimate
0,0,0,0,59141778.0,Non Owner Occupied,https://photos.zillowstatic.com/fp/8e78d9c3127...,True,/homedetails/9-Robken-Rd-Roslindale-MA-02131/5...,Sold,"9 Robken Rd, Roslindale, MA 02131",...,MA,42.293304,-71.133570,819500.0,1.709626e+12,2.0,3.0,1224.0,SINGLE_FAMILY,3999.0
1,1,1,1,59172422.0,RecentChange,https://photos.zillowstatic.com/fp/17fa75ec2c3...,True,/homedetails/130-Appleton-St-APT-2A-Boston-MA-...,Sold,"130 Appleton St APT 2A, Boston, MA 02116",...,MA,42.344826,-71.074990,880000.0,1.709626e+12,1.0,1.0,723.0,CONDO,3634.0
2,3,3,3,59109603.0,RecentChange,https://photos.zillowstatic.com/fp/72bb4e8b21a...,True,/homedetails/64-Bakersfield-St-Dorchester-MA-0...,Sold,"64 Bakersfield St, Dorchester, MA 02125",...,MA,42.315850,-71.061130,1250000.0,1.709539e+12,3.0,6.0,3396.0,MULTI_FAMILY,6000.0
3,4,4,4,59110140.0,RecentChange,https://photos.zillowstatic.com/fp/831ef787fbd...,True,/homedetails/123-Norwell-St-Dorchester-MA-0212...,Sold,"123 Norwell St, Dorchester, MA 02121",...,MA,42.298183,-71.078870,805000.0,1.709539e+12,3.0,4.0,2400.0,MULTI_FAMILY,4964.0
4,5,5,5,59111749.0,RecentChange,https://photos.zillowstatic.com/fp/d7cc4b52033...,True,/homedetails/8-Fowler-St-Dorchester-MA-02121/5...,Sold,"8 Fowler St, Dorchester, MA 02121",...,MA,42.300050,-71.083694,650000.0,1.709539e+12,3.0,9.0,4107.0,MULTI_FAMILY,8970.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6201,7497,7497,495,486407.0,RecentChange,https://photos.zillowstatic.com/fp/5ff72887932...,True,/homedetails/308-Quackenbos-St-NW-Washington-D...,Sold,"308 Quackenbos St NW, Washington, DC 20011",...,DC,38.963560,-77.016990,1125000.0,1.707293e+12,4.0,5.0,2366.0,SINGLE_FAMILY,4999.0
6202,7498,7498,496,489212.0,RecentChange,https://photos.zillowstatic.com/fp/e737d276b55...,True,/homedetails/5108-N-Capitol-St-NW-Washington-D...,Sold,"5108 N Capitol St NW, Washington, DC 20011",...,DC,38.952750,-77.009360,465000.0,1.707293e+12,3.0,3.0,1802.0,TOWNHOUSE,3449.0
6203,7499,7499,497,496388.0,RecentChange,https://photos.zillowstatic.com/fp/21bb2c27339...,True,/homedetails/3110-10th-St-NE-Washington-DC-200...,Sold,"3110 10th St NE, Washington, DC 20017",...,DC,38.928920,-76.992680,1020000.0,1.707293e+12,4.0,4.0,2875.0,SINGLE_FAMILY,4749.0
6204,7500,7500,498,508533.0,Non Owner Occupied,https://maps.googleapis.com/maps/api/staticmap...,NaN,/homedetails/331-16th-St-NE-Washington-DC-2000...,Sold,"331 16th St NE, Washington, DC 20002",...,DC,38.894318,-76.981830,550000.0,1.707293e+12,2.5,4.0,1260.0,SINGLE_FAMILY,3994.0
6205,7501,7501,499,513167.0,RecentChange,https://photos.zillowstatic.com/fp/5e8a4c011dd...,True,/homedetails/5218-Hayes-St-NE-Washington-DC-20...,Sold,"5218 Hayes St NE, Washington, DC 20019",...,DC,38.899930,-76.925570,370000.0,1.707293e+12,2.0,3.0,1264.0,SINGLE_FAMILY,2949.0

We reviewed each column thoroughly and removed those that we felt did not contribute significantly to predicting the price.

Deleting index, Unnamed: 0.1, Unnamed: 0, zpid because they are unnecesary features

In [100]:
deletingColsDf=df[['index', 'Unnamed: 0.1', 'Unnamed: 0', 'zpid', 'imgSrc']]
df.drop(columns=['index', 'Unnamed: 0.1', 'Unnamed: 0', 'zpid', 'imgSrc'], inplace=True)
deletingColsDf

,index,Unnamed: 0.1,Unnamed: 0,zpid,imgSrc
0,0,0,0,59141778.0,https://photos.zillowstatic.com/fp/8e78d9c3127...
1,1,1,1,59172422.0,https://photos.zillowstatic.com/fp/17fa75ec2c3...
2,3,3,3,59109603.0,https://photos.zillowstatic.com/fp/72bb4e8b21a...
3,4,4,4,59110140.0,https://photos.zillowstatic.com/fp/831ef787fbd...
4,5,5,5,59111749.0,https://photos.zillowstatic.com/fp/d7cc4b52033...
...,...,...,...,...,...
6201,7497,7497,495,486407.0,https://photos.zillowstatic.com/fp/5ff72887932...
6202,7498,7498,496,489212.0,https://photos.zillowstatic.com/fp/e737d276b55...
6203,7499,7499,497,496388.0,https://photos.zillowstatic.com/fp/21bb2c27339...
6204,7500,7500,498,508533.0,https://maps.googleapis.com/maps/api/staticmap...
6205,7501,7501,499,513167.0,https://photos.zillowstatic.com/fp/5e8a4c011dd...

Deleting 'hdpData.homeInfo.latitude', 'hdpData.homeInfo.longitude','hdpData.homeInfo.bathrooms','hdpData.homeInfo.bedrooms', 'hdpData.homeInfo.livingArea','hdpData.homeInfo.zpid' as they are  duplicate features

In [101]:
deletingColsDf = df[['hdpData.homeInfo.latitude', 'hdpData.homeInfo.longitude',
                     'hdpData.homeInfo.bathrooms', 'hdpData.homeInfo.bedrooms',
                     'hdpData.homeInfo.livingArea', 'hdpData.homeInfo.zpid']]

df.drop(columns=['hdpData.homeInfo.latitude', 'hdpData.homeInfo.longitude',
                 'hdpData.homeInfo.bathrooms', 'hdpData.homeInfo.bedrooms',
                 'hdpData.homeInfo.livingArea', 'hdpData.homeInfo.zpid'], inplace=True)

deletingColsDf

,hdpData.homeInfo.latitude,hdpData.homeInfo.longitude,hdpData.homeInfo.bathrooms,hdpData.homeInfo.bedrooms,hdpData.homeInfo.livingArea,hdpData.homeInfo.zpid
0,42.293304,-71.133570,2.0,3.0,1224.0,59141778.0
1,42.344826,-71.074990,1.0,1.0,723.0,59172422.0
2,42.315850,-71.061130,3.0,6.0,3396.0,59109603.0
3,42.298183,-71.078870,3.0,4.0,2400.0,59110140.0
4,42.300050,-71.083694,3.0,9.0,4107.0,59111749.0
...,...,...,...,...,...,...
6201,38.963560,-77.016990,4.0,5.0,2366.0,486407.0
6202,38.952750,-77.009360,3.0,3.0,1802.0,489212.0
6203,38.928920,-76.992680,4.0,4.0,2875.0,496388.0
6204,38.894318,-76.981830,2.5,4.0,1260.0,508533.0
6205,38.899930,-76.925570,2.0,3.0,1264.0,513167.0

Deleting hdpData.homeInfo.dateSold as it is not a date and we couldn't find any interpretations from it

In [102]:
deletingColsDf = df[['hdpData.homeInfo.dateSold']]

df.drop(columns=['hdpData.homeInfo.dateSold'], inplace=True)

deletingColsDf

      hdpData.homeInfo.dateSold
0                  1.709626e+12
1                  1.709626e+12
2                  1.709539e+12
3                  1.709539e+12
4                  1.709539e+12
...                         ...
6201               1.707293e+12
6202               1.707293e+12
6203               1.707293e+12
6204               1.707293e+12
6205               1.707293e+12

[6206 rows x 1 columns]

Deleting address,detailUrl as the information in it is already present in other features like streetName and city name

In [103]:
deletingColsDf = df[['address', "detailUrl"]]

df.drop(columns=["address", "detailUrl"], inplace=True)

deletingColsDf

,address,detailUrl
0,"9 Robken Rd, Roslindale, MA 02131",/homedetails/9-Robken-Rd-Roslindale-MA-02131/5...
1,"130 Appleton St APT 2A, Boston, MA 02116",/homedetails/130-Appleton-St-APT-2A-Boston-MA-...
2,"64 Bakersfield St, Dorchester, MA 02125",/homedetails/64-Bakersfield-St-Dorchester-MA-0...
3,"123 Norwell St, Dorchester, MA 02121",/homedetails/123-Norwell-St-Dorchester-MA-0212...
4,"8 Fowler St, Dorchester, MA 02121",/homedetails/8-Fowler-St-Dorchester-MA-02121/5...
...,...,...
6201,"308 Quackenbos St NW, Washington, DC 20011",/homedetails/308-Quackenbos-St-NW-Washington-D...
6202,"5108 N Capitol St NW, Washington, DC 20011",/homedetails/5108-N-Capitol-St-NW-Washington-D...
6203,"3110 10th St NE, Washington, DC 20017",/homedetails/3110-10th-St-NE-Washington-DC-200...
6204,"331 16th St NE, Washington, DC 20002",/homedetails/331-16th-St-NE-Washington-DC-2000...
6205,"5218 Hayes St NE, Washington, DC 20019",/homedetails/5218-Hayes-St-NE-Washington-DC-20...

Deleting street address, zipcode as each row is unique

In [104]:
deletingColsDf = df[['hdpData.homeInfo.streetAddress', 'hdpData.homeInfo.zipcode']]

df.drop(columns=['hdpData.homeInfo.streetAddress', 'hdpData.homeInfo.zipcode'], inplace=True)

deletingColsDf

     hdpData.homeInfo.streetAddress  hdpData.homeInfo.zipcode
0                       9 Robken Rd                    2131.0
1            130 Appleton St APT 2A                    2116.0
2                 64 Bakersfield St                    2125.0
3                    123 Norwell St                    2121.0
4                       8 Fowler St                    2121.0
...                             ...                       ...
6201           308 Quackenbos St NW                   20011.0
6202           5108 N Capitol St NW                   20011.0
6203                3110 10th St NE                   20017.0
6204                 331 16th St NE                   20002.0
6205               5218 Hayes St NE                   20019.0

[6206 rows x 2 columns]

Deleting variableData.text as all the data here is within 2 months and the date is not useful

In [105]:
deletingColsDf = df[["variableData.text"]]

df.drop(columns=["variableData.text"], inplace=True)

deletingColsDf

     variableData.text
0      Sold 03/05/2024
1      Sold 03/05/2024
2      Sold 03/04/2024
3      Sold 03/04/2024
4      Sold 03/04/2024
...                ...
6201   Sold 02/07/2024
6202   Sold 02/07/2024
6203   Sold 02/07/2024
6204   Sold 02/07/2024
6205   Sold 02/07/2024

[6206 rows x 1 columns]

Imputing hasImage null values with false

In [106]:
df["hasImage"].value_counts()

hasImage
True    5894
Name: count, dtype: int64

In [107]:
df["hasImage"].isnull().sum()

312

In [108]:
df["hasImage"].fillna("False",inplace=True)

In [109]:
def removeColPrefix(colName):
    prefixes = ["hdpData.homeInfo.", "latLong."]
    for prefix in prefixes:
        if colName.startswith(prefix):
            colName = colName.replace(prefix, "")
            break  # Exit loop once a prefix is found and removed
    return colName


df.rename(columns={key:removeColPrefix(key) for key in df.columns },inplace=True)

df

,marketingStatusSimplifiedCd,hasImage,statusText,beds,baths,area,sgapt,has3DModel,hasAdditionalAttributions,latitude,longitude,city,state,price,homeType,rentZestimate
0,Non Owner Occupied,True,Sold,3.0,2.0,1224.0,Unknown Listed By,False,True,42.293304,-71.133570,Roslindale,MA,819500.0,SINGLE_FAMILY,3999.0
1,RecentChange,True,Sold,1.0,1.0,723.0,Unknown Listed By,False,True,42.344826,-71.074990,Boston,MA,880000.0,CONDO,3634.0
2,RecentChange,True,Sold,6.0,3.0,3396.0,Unknown Listed By,False,True,42.315850,-71.061130,Dorchester,MA,1250000.0,MULTI_FAMILY,6000.0
3,RecentChange,True,Sold,4.0,3.0,2400.0,Unknown Listed By,False,True,42.298183,-71.078870,Dorchester,MA,805000.0,MULTI_FAMILY,4964.0
4,RecentChange,True,Sold,9.0,3.0,4107.0,RecentChange,False,True,42.300050,-71.083694,Dorchester,MA,650000.0,MULTI_FAMILY,8970.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6201,RecentChange,True,Sold,5.0,4.0,2366.0,Unknown Listed By,False,True,38.963560,-77.016990,Washington,DC,1125000.0,SINGLE_FAMILY,4999.0
6202,RecentChange,True,Sold,3.0,3.0,1802.0,Unknown Listed By,False,True,38.952750,-77.009360,Washington,DC,465000.0,TOWNHOUSE,3449.0
6203,RecentChange,True,Sold,4.0,4.0,2875.0,RecentChange,False,True,38.928920,-76.992680,Washington,DC,1020000.0,SINGLE_FAMILY,4749.0
6204,Non Owner Occupied,False,Sold,4.0,2.5,1260.0,Unknown Listed By,False,False,38.894318,-76.981830,Washington,DC,550000.0,SINGLE_FAMILY,3994.0
6205,RecentChange,True,Sold,3.0,2.0,1264.0,Unknown Listed By,False,True,38.899930,-76.925570,Washington,DC,370000.0,SINGLE_FAMILY,2949.0

Exported the cleaned dataframe

In [110]:
df.to_csv("final_cleaned_data.csv")