In [57]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [58]:
df=pd.read_csv(r'American_house_prices_dataset.csv')
df

,Unnamed: 0.1,Unnamed: 0,zpid,rawHomeStatusCd,marketingStatusSimplifiedCd,imgSrc,hasImage,detailUrl,statusType,statusText,...,info2String,badgeInfo.type,badgeInfo.text,hdpData.homeInfo.listing_sub_type.is_forAuction,isR4R,hdpData.homeInfo.rentalMarketingSubType,communityName,isCdpResult,isComingSoonCommunity,style
0,0,0,59141778.0,Pending,Non Owner Occupied,https://photos.zillowstatic.com/fp/8e78d9c3127...,True,/homedetails/9-Robken-Rd-Roslindale-MA-02131/5...,SOLD,Sold,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1,59172422.0,RecentlySold,RecentChange,https://photos.zillowstatic.com/fp/17fa75ec2c3...,True,/homedetails/130-Appleton-St-APT-2A-Boston-MA-...,SOLD,Sold,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,2,NaN,NaN,NaN,https://photos.zillowstatic.com/fp/db4bb4b2af8...,True,/b/70-leo-m-birmingham-pkwy-brighton-ma-5j3ZG6/,SOLD,For Rent,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,3,59109603.0,RecentlySold,RecentChange,https://photos.zillowstatic.com/fp/72bb4e8b21a...,True,/homedetails/64-Bakersfield-St-Dorchester-MA-0...,SOLD,Sold,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,4,59110140.0,RecentlySold,RecentChange,https://photos.zillowstatic.com/fp/831ef787fbd...,True,/homedetails/123-Norwell-St-Dorchester-MA-0212...,SOLD,Sold,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7498,7498,496,489212.0,RecentlySold,RecentChange,https://photos.zillowstatic.com/fp/e737d276b55...,True,/homedetails/5108-N-Capitol-St-NW-Washington-D...,SOLD,Sold,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7499,7499,497,496388.0,RecentlySold,RecentChange,https://photos.zillowstatic.com/fp/21bb2c27339...,True,/homedetails/3110-10th-St-NE-Washington-DC-200...,SOLD,Sold,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7500,7500,498,508533.0,RecentlySold,Non Owner Occupied,https://maps.googleapis.com/maps/api/staticmap...,NaN,/homedetails/331-16th-St-NE-Washington-DC-2000...,SOLD,Sold,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7501,7501,499,513167.0,RecentlySold,RecentChange,https://photos.zillowstatic.com/fp/5e8a4c011dd...,True,/homedetails/5218-Hayes-St-NE-Washington-DC-20...,SOLD,Sold,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7502,7502,500,NaN,NaN,NaN,https://photos.zillowstatic.com/fp/a4e773c5431...,True,/community/brookland-grove/29726777_plid/,FOR_SALE,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Brookland Grove,True,False,Urban

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7503 entries, 0 to 7502
Columns: 111 entries, Unnamed: 0.1 to style
dtypes: bool(1), float64(32), int64(2), object(76)
memory usage: 6.3+ MB

In [60]:
missingPerc=df.isnull().sum()/df.shape[0]
toomuchmissingCols=missingPerc[missingPerc>0.2].index
toomuchmissingCols

Index(['listingType', 'info6String', 'brokerName', 'timeOnZillow',
       'hdpData.homeInfo.zestimate',
       'hdpData.homeInfo.listing_sub_type.is_FSBA',
       'hdpData.homeInfo.timeOnZillow', 'hdpData.homeInfo.taxAssessedValue',
       'hdpData.homeInfo.lotAreaValue', 'hdpData.homeInfo.lotAreaUnit',
       'hdpData.homeInfo.unit', 'plid', 'minBeds', 'minBaths', 'minArea',
       'lotId', 'buildingId', 'isBuilding', 'canSaveBuilding', 'unitCount',
       'hdpData.homeInfo.datePriceChanged', 'hdpData.homeInfo.priceReduction',
       'hdpData.homeInfo.priceChange', 'buildingName',
       'hdpData.homeInfo.isRentalWithBasePrice', 'availabilityDate',
       'hdpData.homeInfo.listing_sub_type.is_FSBO', 'streetViewURL',
       'streetViewMetadataURL', 'lotAreaString', 'info3String',
       'hdpData.homeInfo.videoCount', 'info1String', 'builderName',
       'hdpData.homeInfo.listing_sub_type.is_newHome',
       'hdpData.homeInfo.providerListingID',
       'hdpData.homeInfo.newConstructionType',
       'hdpData.homeInfo.listing_sub_type.is_openHouse',
       'hdpData.homeInfo.openHouse',
       'hdpData.homeInfo.open_house_info.open_house_showing', 'info2String',
       'badgeInfo.type', 'badgeInfo.text',
       'hdpData.homeInfo.listing_sub_type.is_forAuction', 'isR4R',
       'hdpData.homeInfo.rentalMarketingSubType', 'communityName',
       'isCdpResult', 'isComingSoonCommunity', 'style'],
      dtype='object')

In [61]:
df.drop(columns=toomuchmissingCols,inplace=True)

In [62]:
df.drop(columns=['Unnamed: 0.1','Unnamed: 0'],inplace=True
        )

In [63]:
df.iloc[:,:10]
# zpid, imgSrc, priceLabel, price

,zpid,rawHomeStatusCd,marketingStatusSimplifiedCd,imgSrc,hasImage,detailUrl,statusType,statusText,price,priceLabel
0,59141778.0,Pending,Non Owner Occupied,https://photos.zillowstatic.com/fp/8e78d9c3127...,True,/homedetails/9-Robken-Rd-Roslindale-MA-02131/5...,SOLD,Sold,"$819,500",$820K
1,59172422.0,RecentlySold,RecentChange,https://photos.zillowstatic.com/fp/17fa75ec2c3...,True,/homedetails/130-Appleton-St-APT-2A-Boston-MA-...,SOLD,Sold,"$880,000",$880K
2,NaN,NaN,NaN,https://photos.zillowstatic.com/fp/db4bb4b2af8...,True,/b/70-leo-m-birmingham-pkwy-brighton-ma-5j3ZG6/,SOLD,For Rent,NaN,NaN
3,59109603.0,RecentlySold,RecentChange,https://photos.zillowstatic.com/fp/72bb4e8b21a...,True,/homedetails/64-Bakersfield-St-Dorchester-MA-0...,SOLD,Sold,$1.25M,$1.25M
4,59110140.0,RecentlySold,RecentChange,https://photos.zillowstatic.com/fp/831ef787fbd...,True,/homedetails/123-Norwell-St-Dorchester-MA-0212...,SOLD,Sold,"$805,000",$805K
...,...,...,...,...,...,...,...,...,...,...
7498,489212.0,RecentlySold,RecentChange,https://photos.zillowstatic.com/fp/e737d276b55...,True,/homedetails/5108-N-Capitol-St-NW-Washington-D...,SOLD,Sold,"$465,000",$465K
7499,496388.0,RecentlySold,RecentChange,https://photos.zillowstatic.com/fp/21bb2c27339...,True,/homedetails/3110-10th-St-NE-Washington-DC-200...,SOLD,Sold,$1.02M,$1.02M
7500,508533.0,RecentlySold,Non Owner Occupied,https://maps.googleapis.com/maps/api/staticmap...,NaN,/homedetails/331-16th-St-NE-Washington-DC-2000...,SOLD,Sold,"$550,000",$550K
7501,513167.0,RecentlySold,RecentChange,https://photos.zillowstatic.com/fp/5e8a4c011dd...,True,/homedetails/5218-Hayes-St-NE-Washington-DC-20...,SOLD,Sold,"$370,000",$370K
7502,NaN,NaN,NaN,https://photos.zillowstatic.com/fp/a4e773c5431...,True,/community/brookland-grove/29726777_plid/,FOR_SALE,NaN,"From $859,900",NaN

In [64]:
df.iloc[:,11:20]

,beds,baths,area,isUserClaimingOwner,isUserConfirmedClaim,pgapt,sgapt,shouldShowZestimateAsPrice,has3DModel
0,3.0,2.0,1224.0,False,False,Pending,Unknown Listed By,False,False
1,1.0,1.0,723.0,False,False,RecentlySold,Unknown Listed By,False,False
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
3,6.0,3.0,3396.0,False,False,RecentlySold,Unknown Listed By,False,False
4,4.0,3.0,2400.0,False,False,RecentlySold,Unknown Listed By,False,False
...,...,...,...,...,...,...,...,...,...
7498,3.0,3.0,1802.0,False,False,RecentlySold,Unknown Listed By,False,False
7499,4.0,4.0,2875.0,False,False,RecentlySold,RecentChange,False,False
7500,4.0,2.5,1260.0,False,False,RecentlySold,Unknown Listed By,False,False
7501,3.0,2.0,1264.0,False,False,RecentlySold,Unknown Listed By,False,False
7502,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True

In [65]:
df.iloc[:,21:30]

,isHomeRec,hasAdditionalAttributions,isFeaturedListing,isShowcaseListing,isFavorite,visited,latLong.latitude,latLong.longitude,variableData.type
0,False,True,False,False,False,False,42.293304,-71.133570,RECENTLY_SOLD
1,False,True,False,False,False,False,42.344826,-71.074990,RECENTLY_SOLD
2,False,False,True,False,False,NaN,42.359146,-71.146850,NaN
3,False,True,False,False,False,False,42.315850,-71.061130,RECENTLY_SOLD
4,False,True,False,False,False,False,42.298183,-71.078870,RECENTLY_SOLD
...,...,...,...,...,...,...,...,...,...
7498,False,True,False,False,False,False,38.952750,-77.009360,RECENTLY_SOLD
7499,False,True,False,False,False,False,38.928920,-76.992680,RECENTLY_SOLD
7500,False,False,False,False,False,False,38.894318,-76.981830,RECENTLY_SOLD
7501,False,True,False,False,False,False,38.899930,-76.925570,RECENTLY_SOLD
7502,NaN,NaN,NaN,NaN,NaN,NaN,38.928519,-76.999695,3D_HOME

In [66]:
df.iloc[:,31:40]
# hdpData.homeInfo.latitude,hdpData.homeInfo.longitude , hdpData.homeInfo.dateSold

,hdpData.homeInfo.zpid,hdpData.homeInfo.streetAddress,hdpData.homeInfo.zipcode,hdpData.homeInfo.city,hdpData.homeInfo.state,hdpData.homeInfo.latitude,hdpData.homeInfo.longitude,hdpData.homeInfo.price,hdpData.homeInfo.dateSold
0,59141778.0,9 Robken Rd,2131.0,Roslindale,MA,42.293304,-71.13357,819500.0,1.709626e+12
1,59172422.0,130 Appleton St APT 2A,2116.0,Boston,MA,42.344826,-71.07499,880000.0,1.709626e+12
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,59109603.0,64 Bakersfield St,2125.0,Dorchester,MA,42.315850,-71.06113,1250000.0,1.709539e+12
4,59110140.0,123 Norwell St,2121.0,Dorchester,MA,42.298183,-71.07887,805000.0,1.709539e+12
...,...,...,...,...,...,...,...,...,...
7498,489212.0,5108 N Capitol St NW,20011.0,Washington,DC,38.952750,-77.00936,465000.0,1.707293e+12
7499,496388.0,3110 10th St NE,20017.0,Washington,DC,38.928920,-76.99268,1020000.0,1.707293e+12
7500,508533.0,331 16th St NE,20002.0,Washington,DC,38.894318,-76.98183,550000.0,1.707293e+12
7501,513167.0,5218 Hayes St NE,20019.0,Washington,DC,38.899930,-76.92557,370000.0,1.707293e+12
7502,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [67]:
df.iloc[:,41:50]
# hdpData.homeInfo.bedrooms, hdpData.homeInfo.livingArea

,hdpData.homeInfo.bedrooms,hdpData.homeInfo.livingArea,hdpData.homeInfo.homeType,hdpData.homeInfo.homeStatus,hdpData.homeInfo.daysOnZillow,hdpData.homeInfo.isFeatured,hdpData.homeInfo.shouldHighlight,hdpData.homeInfo.rentZestimate,hdpData.homeInfo.isUnmappable
0,3.0,1224.0,SINGLE_FAMILY,PENDING,-1.0,False,False,3999.0,False
1,1.0,723.0,CONDO,RECENTLY_SOLD,-1.0,False,False,3634.0,False
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,6.0,3396.0,MULTI_FAMILY,RECENTLY_SOLD,-1.0,False,False,6000.0,False
4,4.0,2400.0,MULTI_FAMILY,RECENTLY_SOLD,-1.0,False,False,4964.0,False
...,...,...,...,...,...,...,...,...,...
7498,3.0,1802.0,TOWNHOUSE,RECENTLY_SOLD,-1.0,False,False,3449.0,False
7499,4.0,2875.0,SINGLE_FAMILY,RECENTLY_SOLD,-1.0,False,False,4749.0,False
7500,4.0,1260.0,SINGLE_FAMILY,RECENTLY_SOLD,-1.0,False,False,3994.0,False
7501,3.0,1264.0,SINGLE_FAMILY,RECENTLY_SOLD,-1.0,False,False,2949.0,False
7502,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [68]:
df.iloc[:,51:60]
# hdpData.homeInfo.country

,hdpData.homeInfo.priceForHDP,hdpData.homeInfo.isNonOwnerOccupied,hdpData.homeInfo.isPremierBuilder,hdpData.homeInfo.isZillowOwned,hdpData.homeInfo.currency,hdpData.homeInfo.country,hdpData.homeInfo.isShowcaseListing,hdpData.homeInfo.homeStatusForHDP
0,819500.0,True,False,False,USD,USA,False,NaN
1,880000.0,True,False,False,USD,USA,False,RECENTLY_SOLD
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1250000.0,True,False,False,USD,USA,False,RECENTLY_SOLD
4,805000.0,True,False,False,USD,USA,False,RECENTLY_SOLD
...,...,...,...,...,...,...,...,...
7498,465000.0,True,False,False,USD,USA,False,RECENTLY_SOLD
7499,1020000.0,True,False,False,USD,USA,False,RECENTLY_SOLD
7500,550000.0,True,False,False,USD,USA,False,RECENTLY_SOLD
7501,370000.0,True,False,False,USD,USA,False,RECENTLY_SOLD
7502,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [69]:
firstFilterCols=["hdpData.homeInfo.country","hdpData.homeInfo.bedrooms", "hdpData.homeInfo.livingArea",
                 "hdpData.homeInfo.latitude","hdpData.homeInfo.longitude" , "hdpData.homeInfo.dateSold",
                 "zpid", "imgSrc", "priceLabel", "price"]

df.drop(columns=firstFilterCols,inplace=True)

In [70]:
df.rename(columns={"hdpData.homeInfo.priceForHDP":"price"},inplace=True)
df.drop(columns=["hdpData.homeInfo.price"],inplace=True)

In [71]:
nullPriceIndices=df["price"][df["price"].isnull()==True].index
df.drop(nullPriceIndices,inplace=True)

In [72]:
df.reset_index(inplace=True)

In [73]:
(df.isnull().sum()/df.shape[0]).sort_values(ascending=False)*100

hasImage                                    5.027393
area                                        3.238801
beds                                        2.997100
hdpData.homeInfo.bathrooms                  2.159201
baths                                       2.159201
variableData.text                           1.176281
variableData.type                           1.176281
hdpData.homeInfo.rentZestimate              0.999033
hdpData.homeInfo.homeStatusForHDP           0.290042
latLong.longitude                           0.016113
latLong.latitude                            0.016113
isUserClaimingOwner                         0.000000
marketingStatusSimplifiedCd                 0.000000
hdpData.homeInfo.state                      0.000000
detailUrl                                   0.000000
hdpData.homeInfo.homeType                   0.000000
hdpData.homeInfo.homeStatus                 0.000000
hdpData.homeInfo.daysOnZillow               0.000000
hdpData.homeInfo.isFeatured                 0.000000
hdpData.homeInfo.shouldHighlight            0.000000
hdpData.homeInfo.isUnmappable               0.000000
isUserConfirmedClaim                        0.000000
hdpData.homeInfo.isPreforeclosureAuction    0.000000
price                                       0.000000
hdpData.homeInfo.isNonOwnerOccupied         0.000000
hdpData.homeInfo.isPremierBuilder           0.000000
hdpData.homeInfo.isZillowOwned              0.000000
hdpData.homeInfo.currency                   0.000000
hdpData.homeInfo.isShowcaseListing          0.000000
hdpData.homeInfo.city                       0.000000
hdpData.homeInfo.zipcode                    0.000000
hdpData.homeInfo.streetAddress              0.000000
hdpData.homeInfo.zpid                       0.000000
pgapt                                       0.000000
sgapt                                       0.000000
shouldShowZestimateAsPrice                  0.000000
has3DModel                                  0.000000
hasVideo                                    0.000000
isHomeRec                                   0.000000
hasAdditionalAttributions                   0.000000
isFeaturedListing                           0.000000
isShowcaseListing                           0.000000
isFavorite                                  0.000000
visited                                     0.000000
rawHomeStatusCd                             0.000000
address                                     0.000000
statusText                                  0.000000
statusType                                  0.000000
index                                       0.000000
dtype: float64

In [74]:
df.drop(columns=["index"],inplace=True)

In [75]:
df

,rawHomeStatusCd,marketingStatusSimplifiedCd,hasImage,detailUrl,statusType,statusText,address,beds,baths,area,...,hdpData.homeInfo.rentZestimate,hdpData.homeInfo.isUnmappable,hdpData.homeInfo.isPreforeclosureAuction,price,hdpData.homeInfo.isNonOwnerOccupied,hdpData.homeInfo.isPremierBuilder,hdpData.homeInfo.isZillowOwned,hdpData.homeInfo.currency,hdpData.homeInfo.isShowcaseListing,hdpData.homeInfo.homeStatusForHDP
0,Pending,Non Owner Occupied,True,/homedetails/9-Robken-Rd-Roslindale-MA-02131/5...,SOLD,Sold,"9 Robken Rd, Roslindale, MA 02131",3.0,2.0,1224.0,...,3999.0,False,False,819500.0,True,False,False,USD,False,NaN
1,RecentlySold,RecentChange,True,/homedetails/130-Appleton-St-APT-2A-Boston-MA-...,SOLD,Sold,"130 Appleton St APT 2A, Boston, MA 02116",1.0,1.0,723.0,...,3634.0,False,False,880000.0,True,False,False,USD,False,RECENTLY_SOLD
2,RecentlySold,RecentChange,True,/homedetails/64-Bakersfield-St-Dorchester-MA-0...,SOLD,Sold,"64 Bakersfield St, Dorchester, MA 02125",6.0,3.0,3396.0,...,6000.0,False,False,1250000.0,True,False,False,USD,False,RECENTLY_SOLD
3,RecentlySold,RecentChange,True,/homedetails/123-Norwell-St-Dorchester-MA-0212...,SOLD,Sold,"123 Norwell St, Dorchester, MA 02121",4.0,3.0,2400.0,...,4964.0,False,False,805000.0,True,False,False,USD,False,RECENTLY_SOLD
4,RecentlySold,RecentChange,True,/homedetails/8-Fowler-St-Dorchester-MA-02121/5...,SOLD,Sold,"8 Fowler St, Dorchester, MA 02121",9.0,3.0,4107.0,...,8970.0,False,False,650000.0,True,False,False,USD,False,RECENTLY_SOLD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6201,RecentlySold,RecentChange,True,/homedetails/308-Quackenbos-St-NW-Washington-D...,SOLD,Sold,"308 Quackenbos St NW, Washington, DC 20011",5.0,4.0,2366.0,...,4999.0,False,False,1125000.0,True,False,False,USD,False,RECENTLY_SOLD
6202,RecentlySold,RecentChange,True,/homedetails/5108-N-Capitol-St-NW-Washington-D...,SOLD,Sold,"5108 N Capitol St NW, Washington, DC 20011",3.0,3.0,1802.0,...,3449.0,False,False,465000.0,True,False,False,USD,False,RECENTLY_SOLD
6203,RecentlySold,RecentChange,True,/homedetails/3110-10th-St-NE-Washington-DC-200...,SOLD,Sold,"3110 10th St NE, Washington, DC 20017",4.0,4.0,2875.0,...,4749.0,False,False,1020000.0,True,False,False,USD,False,RECENTLY_SOLD
6204,RecentlySold,Non Owner Occupied,NaN,/homedetails/331-16th-St-NE-Washington-DC-2000...,SOLD,Sold,"331 16th St NE, Washington, DC 20002",4.0,2.5,1260.0,...,3994.0,False,False,550000.0,True,False,False,USD,False,RECENTLY_SOLD
6205,RecentlySold,RecentChange,True,/homedetails/5218-Hayes-St-NE-Washington-DC-20...,SOLD,Sold,"5218 Hayes St NE, Washington, DC 20019",3.0,2.0,1264.0,...,2949.0,False,False,370000.0,True,False,False,USD,False,RECENTLY_SOLD

In [76]:
# row wise sum
df.isnull().sum(axis=1)

0       1
1       0
2       0
3       0
4       0
       ..
6201    0
6202    0
6203    0
6204    1
6205    0
Length: 6206, dtype: int64

In [77]:
df.hasImage.unique()

array([True, nan], dtype=object)

In [78]:
df["hasImage"].fillna(False,inplace=True)

In [79]:
df.hasImage.unique()

array([ True, False])

In [80]:
(df.isnull().sum()/df.shape[0]).sort_values(ascending=False)*100

area                                        3.238801
beds                                        2.997100
hdpData.homeInfo.bathrooms                  2.159201
baths                                       2.159201
variableData.text                           1.176281
variableData.type                           1.176281
hdpData.homeInfo.rentZestimate              0.999033
hdpData.homeInfo.homeStatusForHDP           0.290042
latLong.latitude                            0.016113
latLong.longitude                           0.016113
isUserClaimingOwner                         0.000000
hasImage                                    0.000000
hdpData.homeInfo.state                      0.000000
detailUrl                                   0.000000
hdpData.homeInfo.homeType                   0.000000
hdpData.homeInfo.homeStatus                 0.000000
hdpData.homeInfo.daysOnZillow               0.000000
hdpData.homeInfo.isFeatured                 0.000000
hdpData.homeInfo.shouldHighlight            0.000000
hdpData.homeInfo.isUnmappable               0.000000
isUserConfirmedClaim                        0.000000
hdpData.homeInfo.isPreforeclosureAuction    0.000000
price                                       0.000000
hdpData.homeInfo.isNonOwnerOccupied         0.000000
hdpData.homeInfo.isPremierBuilder           0.000000
hdpData.homeInfo.isZillowOwned              0.000000
hdpData.homeInfo.currency                   0.000000
hdpData.homeInfo.isShowcaseListing          0.000000
hdpData.homeInfo.city                       0.000000
hdpData.homeInfo.zipcode                    0.000000
hdpData.homeInfo.streetAddress              0.000000
hdpData.homeInfo.zpid                       0.000000
pgapt                                       0.000000
sgapt                                       0.000000
shouldShowZestimateAsPrice                  0.000000
has3DModel                                  0.000000
hasVideo                                    0.000000
isHomeRec                                   0.000000
hasAdditionalAttributions                   0.000000
isFeaturedListing                           0.000000
isShowcaseListing                           0.000000
isFavorite                                  0.000000
visited                                     0.000000
address                                     0.000000
marketingStatusSimplifiedCd                 0.000000
statusText                                  0.000000
statusType                                  0.000000
rawHomeStatusCd                             0.000000
dtype: float64

In [81]:
df.area

0       1224.0
1        723.0
2       3396.0
3       2400.0
4       4107.0
         ...
6201    2366.0
6202    1802.0
6203    2875.0
6204    1260.0
6205    1264.0
Name: area, Length: 6206, dtype: float64

In [82]:
(df["baths"]==df["hdpData.homeInfo.bathrooms"])[(df["baths"]==df["hdpData.homeInfo.bathrooms"])]

0       True
1       True
2       True
3       True
4       True
        ...
6201    True
6202    True
6203    True
6204    True
6205    True
Length: 6066, dtype: bool

In [83]:
df[(df["baths"]==df["hdpData.homeInfo.bathrooms"])==False]

,rawHomeStatusCd,marketingStatusSimplifiedCd,hasImage,detailUrl,statusType,statusText,address,beds,baths,area,...,hdpData.homeInfo.rentZestimate,hdpData.homeInfo.isUnmappable,hdpData.homeInfo.isPreforeclosureAuction,price,hdpData.homeInfo.isNonOwnerOccupied,hdpData.homeInfo.isPremierBuilder,hdpData.homeInfo.isZillowOwned,hdpData.homeInfo.currency,hdpData.homeInfo.isShowcaseListing,hdpData.homeInfo.homeStatusForHDP
298,RecentlySold,Non Owner Occupied,True,/homedetails/530-Vfw-Pkwy-West-Roxbury-MA-0213...,SOLD,Sold,"530 Vfw Pkwy, West Roxbury, MA 02132",NaN,NaN,23994.0,...,13070.0,False,False,6718000.0,True,False,False,USD,False,RECENTLY_SOLD
357,RecentlySold,RecentChange,True,/homedetails/4731-Whispering-Oaks-Dr-Charlotte...,SOLD,Sold,"4731 Whispering Oaks Dr, Charlotte, NC 28213",NaN,NaN,NaN,...,1994.0,False,False,110000.0,True,False,False,USD,False,RECENTLY_SOLD
361,RecentlySold,RecentChange,True,/homedetails/8309-Starnes-Randall-Rd-Charlotte...,SOLD,Sold,"8309 Starnes Randall Rd, Charlotte, NC 28215",NaN,NaN,NaN,...,1977.0,False,False,350000.0,True,False,False,USD,False,RECENTLY_SOLD
406,RecentlySold,RecentChange,True,/homedetails/1-Starnes-Randall-Rd-Charlotte-NC...,SOLD,Sold,"1 Starnes Randall Rd, Charlotte, NC 28215",NaN,NaN,NaN,...,1970.0,False,False,245000.0,True,False,False,USD,False,RECENTLY_SOLD
407,RecentlySold,RecentChange,True,/homedetails/2-Starnes-Randall-Rd-Charlotte-NC...,SOLD,Sold,"2 Starnes Randall Rd, Charlotte, NC 28215",NaN,NaN,NaN,...,1970.0,False,False,130000.0,True,False,False,USD,False,RECENTLY_SOLD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5938,RecentlySold,RecentChange,True,/homedetails/213-Adams-St-NE-Washington-DC-200...,SOLD,Sold,"213 Adams St NE, Washington, DC 20002",4.0,NaN,2720.0,...,4999.0,False,False,920000.0,True,False,False,USD,False,RECENTLY_SOLD
6041,RecentlySold,RecentChange,False,/homedetails/23-R-St-NW-Washington-DC-20001/47...,SOLD,Sold,"23 R St NW, Washington, DC 20001",4.0,NaN,2314.0,...,4999.0,False,False,825000.0,True,False,False,USD,False,RECENTLY_SOLD
6096,RecentlySold,RecentChange,True,/homedetails/2221-Kearny-St-NE-Washington-DC-2...,SOLD,Sold,"2221 Kearny St NE, Washington, DC 20018",3.0,NaN,0.0,...,1875.0,False,False,800000.0,True,False,False,USD,False,RECENTLY_SOLD
6112,RecentlySold,RecentChange,True,/homedetails/3315-Nash-Pl-SE-Washington-DC-200...,SOLD,Sold,"3315 Nash Pl SE, Washington, DC 20020",NaN,NaN,NaN,...,1749.0,False,False,100000.0,True,False,False,USD,False,RECENTLY_SOLD
6167,RecentlySold,RecentChange,True,/homedetails/1230-Penn-St-NE-Washington-DC-200...,SOLD,Sold,"1230 Penn St NE, Washington, DC 20002",8.0,NaN,3164.0,...,6999.0,False,False,875000.0,True,False,False,USD,False,RECENTLY_SOLD

In [84]:
df[["baths","hdpData.homeInfo.bathrooms"]][(df["baths"]==df["hdpData.homeInfo.bathrooms"])==False].value_counts()

baths  hdpData.homeInfo.bathrooms
2.67   2.67                          2
1.10   1.10                          1
2.10   2.10                          1
2.33   2.33                          1
3.33   3.33                          1
Name: count, dtype: int64

In [85]:
df.drop(columns=["hdpData.homeInfo.bathrooms"],inplace=True)

In [86]:
df

,rawHomeStatusCd,marketingStatusSimplifiedCd,hasImage,detailUrl,statusType,statusText,address,beds,baths,area,...,hdpData.homeInfo.rentZestimate,hdpData.homeInfo.isUnmappable,hdpData.homeInfo.isPreforeclosureAuction,price,hdpData.homeInfo.isNonOwnerOccupied,hdpData.homeInfo.isPremierBuilder,hdpData.homeInfo.isZillowOwned,hdpData.homeInfo.currency,hdpData.homeInfo.isShowcaseListing,hdpData.homeInfo.homeStatusForHDP
0,Pending,Non Owner Occupied,True,/homedetails/9-Robken-Rd-Roslindale-MA-02131/5...,SOLD,Sold,"9 Robken Rd, Roslindale, MA 02131",3.0,2.0,1224.0,...,3999.0,False,False,819500.0,True,False,False,USD,False,NaN
1,RecentlySold,RecentChange,True,/homedetails/130-Appleton-St-APT-2A-Boston-MA-...,SOLD,Sold,"130 Appleton St APT 2A, Boston, MA 02116",1.0,1.0,723.0,...,3634.0,False,False,880000.0,True,False,False,USD,False,RECENTLY_SOLD
2,RecentlySold,RecentChange,True,/homedetails/64-Bakersfield-St-Dorchester-MA-0...,SOLD,Sold,"64 Bakersfield St, Dorchester, MA 02125",6.0,3.0,3396.0,...,6000.0,False,False,1250000.0,True,False,False,USD,False,RECENTLY_SOLD
3,RecentlySold,RecentChange,True,/homedetails/123-Norwell-St-Dorchester-MA-0212...,SOLD,Sold,"123 Norwell St, Dorchester, MA 02121",4.0,3.0,2400.0,...,4964.0,False,False,805000.0,True,False,False,USD,False,RECENTLY_SOLD
4,RecentlySold,RecentChange,True,/homedetails/8-Fowler-St-Dorchester-MA-02121/5...,SOLD,Sold,"8 Fowler St, Dorchester, MA 02121",9.0,3.0,4107.0,...,8970.0,False,False,650000.0,True,False,False,USD,False,RECENTLY_SOLD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6201,RecentlySold,RecentChange,True,/homedetails/308-Quackenbos-St-NW-Washington-D...,SOLD,Sold,"308 Quackenbos St NW, Washington, DC 20011",5.0,4.0,2366.0,...,4999.0,False,False,1125000.0,True,False,False,USD,False,RECENTLY_SOLD
6202,RecentlySold,RecentChange,True,/homedetails/5108-N-Capitol-St-NW-Washington-D...,SOLD,Sold,"5108 N Capitol St NW, Washington, DC 20011",3.0,3.0,1802.0,...,3449.0,False,False,465000.0,True,False,False,USD,False,RECENTLY_SOLD
6203,RecentlySold,RecentChange,True,/homedetails/3110-10th-St-NE-Washington-DC-200...,SOLD,Sold,"3110 10th St NE, Washington, DC 20017",4.0,4.0,2875.0,...,4749.0,False,False,1020000.0,True,False,False,USD,False,RECENTLY_SOLD
6204,RecentlySold,Non Owner Occupied,False,/homedetails/331-16th-St-NE-Washington-DC-2000...,SOLD,Sold,"331 16th St NE, Washington, DC 20002",4.0,2.5,1260.0,...,3994.0,False,False,550000.0,True,False,False,USD,False,RECENTLY_SOLD
6205,RecentlySold,RecentChange,True,/homedetails/5218-Hayes-St-NE-Washington-DC-20...,SOLD,Sold,"5218 Hayes St NE, Washington, DC 20019",3.0,2.0,1264.0,...,2949.0,False,False,370000.0,True,False,False,USD,False,RECENTLY_SOLD

In [87]:
df.drop(columns=["address"],inplace=True)

In [88]:
df

,rawHomeStatusCd,marketingStatusSimplifiedCd,hasImage,detailUrl,statusType,statusText,beds,baths,area,isUserClaimingOwner,...,hdpData.homeInfo.rentZestimate,hdpData.homeInfo.isUnmappable,hdpData.homeInfo.isPreforeclosureAuction,price,hdpData.homeInfo.isNonOwnerOccupied,hdpData.homeInfo.isPremierBuilder,hdpData.homeInfo.isZillowOwned,hdpData.homeInfo.currency,hdpData.homeInfo.isShowcaseListing,hdpData.homeInfo.homeStatusForHDP
0,Pending,Non Owner Occupied,True,/homedetails/9-Robken-Rd-Roslindale-MA-02131/5...,SOLD,Sold,3.0,2.0,1224.0,False,...,3999.0,False,False,819500.0,True,False,False,USD,False,NaN
1,RecentlySold,RecentChange,True,/homedetails/130-Appleton-St-APT-2A-Boston-MA-...,SOLD,Sold,1.0,1.0,723.0,False,...,3634.0,False,False,880000.0,True,False,False,USD,False,RECENTLY_SOLD
2,RecentlySold,RecentChange,True,/homedetails/64-Bakersfield-St-Dorchester-MA-0...,SOLD,Sold,6.0,3.0,3396.0,False,...,6000.0,False,False,1250000.0,True,False,False,USD,False,RECENTLY_SOLD
3,RecentlySold,RecentChange,True,/homedetails/123-Norwell-St-Dorchester-MA-0212...,SOLD,Sold,4.0,3.0,2400.0,False,...,4964.0,False,False,805000.0,True,False,False,USD,False,RECENTLY_SOLD
4,RecentlySold,RecentChange,True,/homedetails/8-Fowler-St-Dorchester-MA-02121/5...,SOLD,Sold,9.0,3.0,4107.0,False,...,8970.0,False,False,650000.0,True,False,False,USD,False,RECENTLY_SOLD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6201,RecentlySold,RecentChange,True,/homedetails/308-Quackenbos-St-NW-Washington-D...,SOLD,Sold,5.0,4.0,2366.0,False,...,4999.0,False,False,1125000.0,True,False,False,USD,False,RECENTLY_SOLD
6202,RecentlySold,RecentChange,True,/homedetails/5108-N-Capitol-St-NW-Washington-D...,SOLD,Sold,3.0,3.0,1802.0,False,...,3449.0,False,False,465000.0,True,False,False,USD,False,RECENTLY_SOLD
6203,RecentlySold,RecentChange,True,/homedetails/3110-10th-St-NE-Washington-DC-200...,SOLD,Sold,4.0,4.0,2875.0,False,...,4749.0,False,False,1020000.0,True,False,False,USD,False,RECENTLY_SOLD
6204,RecentlySold,Non Owner Occupied,False,/homedetails/331-16th-St-NE-Washington-DC-2000...,SOLD,Sold,4.0,2.5,1260.0,False,...,3994.0,False,False,550000.0,True,False,False,USD,False,RECENTLY_SOLD
6205,RecentlySold,RecentChange,True,/homedetails/5218-Hayes-St-NE-Washington-DC-20...,SOLD,Sold,3.0,2.0,1264.0,False,...,2949.0,False,False,370000.0,True,False,False,USD,False,RECENTLY_SOLD

In [89]:
df.columns

Index(['rawHomeStatusCd', 'marketingStatusSimplifiedCd', 'hasImage',
       'detailUrl', 'statusType', 'statusText', 'beds', 'baths', 'area',
       'isUserClaimingOwner', 'isUserConfirmedClaim', 'pgapt', 'sgapt',
       'shouldShowZestimateAsPrice', 'has3DModel', 'hasVideo', 'isHomeRec',
       'hasAdditionalAttributions', 'isFeaturedListing', 'isShowcaseListing',
       'isFavorite', 'visited', 'latLong.latitude', 'latLong.longitude',
       'variableData.type', 'variableData.text', 'hdpData.homeInfo.zpid',
       'hdpData.homeInfo.streetAddress', 'hdpData.homeInfo.zipcode',
       'hdpData.homeInfo.city', 'hdpData.homeInfo.state',
       'hdpData.homeInfo.homeType', 'hdpData.homeInfo.homeStatus',
       'hdpData.homeInfo.daysOnZillow', 'hdpData.homeInfo.isFeatured',
       'hdpData.homeInfo.shouldHighlight', 'hdpData.homeInfo.rentZestimate',
       'hdpData.homeInfo.isUnmappable',
       'hdpData.homeInfo.isPreforeclosureAuction', 'price',
       'hdpData.homeInfo.isNonOwnerOccupied',
       'hdpData.homeInfo.isPremierBuilder', 'hdpData.homeInfo.isZillowOwned',
       'hdpData.homeInfo.currency', 'hdpData.homeInfo.isShowcaseListing',
       'hdpData.homeInfo.homeStatusForHDP'],
      dtype='object')

In [90]:
(df.columns=="isShowcaseListing").sum()

1

In [91]:
# df.columns
# def removeColPrefix(colName):
#     prefixes=["hdpData.homeInfo.","latLong."]
#     for prefix in prefixes:
#         colName=colName.replace(prefix,"")
#     return colName
# df.rename(columns=lambda x: removeColPrefix(x),inplace=True)
# df = df.T.drop_duplicates().T

In [92]:

tooMuch1Category=[]
for col in df.columns:
    maxVal=df[col].value_counts().sort_values(ascending=False).index[0]

    maxValProportion=df[col][df[col]==maxVal].shape[0]/df[col].shape[0]
    
    if maxValProportion>0.995:
        tooMuch1Category.append(col)
print(tooMuch1Category)

['rawHomeStatusCd', 'statusType', 'isUserClaimingOwner', 'isUserConfirmedClaim', 'pgapt', 'shouldShowZestimateAsPrice', 'isHomeRec', 'isFeaturedListing', 'isShowcaseListing', 'isFavorite', 'visited', 'hdpData.homeInfo.homeStatus', 'hdpData.homeInfo.daysOnZillow', 'hdpData.homeInfo.isFeatured', 'hdpData.homeInfo.shouldHighlight', 'hdpData.homeInfo.isUnmappable', 'hdpData.homeInfo.isPreforeclosureAuction', 'hdpData.homeInfo.isNonOwnerOccupied', 'hdpData.homeInfo.isPremierBuilder', 'hdpData.homeInfo.isZillowOwned', 'hdpData.homeInfo.currency', 'hdpData.homeInfo.isShowcaseListing']

In [93]:
df.drop(columns=tooMuch1Category,inplace=True)

In [94]:
onlyOneUniqueValue=[]
for col in df.columns:
    if df[col].nunique()==1:
        onlyOneUniqueValue.append(col)
        print(col,df[col].unique()[0])
onlyOneUniqueValue

[]

In [95]:
df

,marketingStatusSimplifiedCd,hasImage,detailUrl,statusText,beds,baths,area,sgapt,has3DModel,hasVideo,...,variableData.text,hdpData.homeInfo.zpid,hdpData.homeInfo.streetAddress,hdpData.homeInfo.zipcode,hdpData.homeInfo.city,hdpData.homeInfo.state,hdpData.homeInfo.homeType,hdpData.homeInfo.rentZestimate,price,hdpData.homeInfo.homeStatusForHDP
0,Non Owner Occupied,True,/homedetails/9-Robken-Rd-Roslindale-MA-02131/5...,Sold,3.0,2.0,1224.0,Unknown Listed By,False,False,...,Sold 03/05/2024,59141778.0,9 Robken Rd,2131.0,Roslindale,MA,SINGLE_FAMILY,3999.0,819500.0,NaN
1,RecentChange,True,/homedetails/130-Appleton-St-APT-2A-Boston-MA-...,Sold,1.0,1.0,723.0,Unknown Listed By,False,False,...,Sold 03/05/2024,59172422.0,130 Appleton St APT 2A,2116.0,Boston,MA,CONDO,3634.0,880000.0,RECENTLY_SOLD
2,RecentChange,True,/homedetails/64-Bakersfield-St-Dorchester-MA-0...,Sold,6.0,3.0,3396.0,Unknown Listed By,False,False,...,Sold 03/04/2024,59109603.0,64 Bakersfield St,2125.0,Dorchester,MA,MULTI_FAMILY,6000.0,1250000.0,RECENTLY_SOLD
3,RecentChange,True,/homedetails/123-Norwell-St-Dorchester-MA-0212...,Sold,4.0,3.0,2400.0,Unknown Listed By,False,False,...,Sold 03/04/2024,59110140.0,123 Norwell St,2121.0,Dorchester,MA,MULTI_FAMILY,4964.0,805000.0,RECENTLY_SOLD
4,RecentChange,True,/homedetails/8-Fowler-St-Dorchester-MA-02121/5...,Sold,9.0,3.0,4107.0,RecentChange,False,False,...,Sold 03/04/2024,59111749.0,8 Fowler St,2121.0,Dorchester,MA,MULTI_FAMILY,8970.0,650000.0,RECENTLY_SOLD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6201,RecentChange,True,/homedetails/308-Quackenbos-St-NW-Washington-D...,Sold,5.0,4.0,2366.0,Unknown Listed By,False,False,...,Sold 02/07/2024,486407.0,308 Quackenbos St NW,20011.0,Washington,DC,SINGLE_FAMILY,4999.0,1125000.0,RECENTLY_SOLD
6202,RecentChange,True,/homedetails/5108-N-Capitol-St-NW-Washington-D...,Sold,3.0,3.0,1802.0,Unknown Listed By,False,False,...,Sold 02/07/2024,489212.0,5108 N Capitol St NW,20011.0,Washington,DC,TOWNHOUSE,3449.0,465000.0,RECENTLY_SOLD
6203,RecentChange,True,/homedetails/3110-10th-St-NE-Washington-DC-200...,Sold,4.0,4.0,2875.0,RecentChange,False,False,...,Sold 02/07/2024,496388.0,3110 10th St NE,20017.0,Washington,DC,SINGLE_FAMILY,4749.0,1020000.0,RECENTLY_SOLD
6204,Non Owner Occupied,False,/homedetails/331-16th-St-NE-Washington-DC-2000...,Sold,4.0,2.5,1260.0,Unknown Listed By,False,False,...,Sold 02/07/2024,508533.0,331 16th St NE,20002.0,Washington,DC,SINGLE_FAMILY,3994.0,550000.0,RECENTLY_SOLD
6205,RecentChange,True,/homedetails/5218-Hayes-St-NE-Washington-DC-20...,Sold,3.0,2.0,1264.0,Unknown Listed By,False,False,...,Sold 02/07/2024,513167.0,5218 Hayes St NE,20019.0,Washington,DC,SINGLE_FAMILY,2949.0,370000.0,RECENTLY_SOLD

In [96]:
df.isnull().mean().sort_values(ascending=False)*100

area                                 3.238801
beds                                 2.997100
baths                                2.159201
variableData.text                    1.176281
variableData.type                    1.176281
hdpData.homeInfo.rentZestimate       0.999033
hdpData.homeInfo.homeStatusForHDP    0.290042
latLong.latitude                     0.016113
latLong.longitude                    0.016113
hasVideo                             0.000000
hasAdditionalAttributions            0.000000
has3DModel                           0.000000
hasImage                             0.000000
sgapt                                0.000000
statusText                           0.000000
hdpData.homeInfo.zpid                0.000000
hdpData.homeInfo.streetAddress       0.000000
hdpData.homeInfo.zipcode             0.000000
hdpData.homeInfo.city                0.000000
hdpData.homeInfo.state               0.000000
hdpData.homeInfo.homeType            0.000000
detailUrl                            0.000000
price                                0.000000
marketingStatusSimplifiedCd          0.000000
dtype: float64

In [97]:
df.drop(columns=["detailUrl"],inplace=True)

In [98]:
df

,marketingStatusSimplifiedCd,hasImage,statusText,beds,baths,area,sgapt,has3DModel,hasVideo,hasAdditionalAttributions,...,variableData.text,hdpData.homeInfo.zpid,hdpData.homeInfo.streetAddress,hdpData.homeInfo.zipcode,hdpData.homeInfo.city,hdpData.homeInfo.state,hdpData.homeInfo.homeType,hdpData.homeInfo.rentZestimate,price,hdpData.homeInfo.homeStatusForHDP
0,Non Owner Occupied,True,Sold,3.0,2.0,1224.0,Unknown Listed By,False,False,True,...,Sold 03/05/2024,59141778.0,9 Robken Rd,2131.0,Roslindale,MA,SINGLE_FAMILY,3999.0,819500.0,NaN
1,RecentChange,True,Sold,1.0,1.0,723.0,Unknown Listed By,False,False,True,...,Sold 03/05/2024,59172422.0,130 Appleton St APT 2A,2116.0,Boston,MA,CONDO,3634.0,880000.0,RECENTLY_SOLD
2,RecentChange,True,Sold,6.0,3.0,3396.0,Unknown Listed By,False,False,True,...,Sold 03/04/2024,59109603.0,64 Bakersfield St,2125.0,Dorchester,MA,MULTI_FAMILY,6000.0,1250000.0,RECENTLY_SOLD
3,RecentChange,True,Sold,4.0,3.0,2400.0,Unknown Listed By,False,False,True,...,Sold 03/04/2024,59110140.0,123 Norwell St,2121.0,Dorchester,MA,MULTI_FAMILY,4964.0,805000.0,RECENTLY_SOLD
4,RecentChange,True,Sold,9.0,3.0,4107.0,RecentChange,False,False,True,...,Sold 03/04/2024,59111749.0,8 Fowler St,2121.0,Dorchester,MA,MULTI_FAMILY,8970.0,650000.0,RECENTLY_SOLD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6201,RecentChange,True,Sold,5.0,4.0,2366.0,Unknown Listed By,False,False,True,...,Sold 02/07/2024,486407.0,308 Quackenbos St NW,20011.0,Washington,DC,SINGLE_FAMILY,4999.0,1125000.0,RECENTLY_SOLD
6202,RecentChange,True,Sold,3.0,3.0,1802.0,Unknown Listed By,False,False,True,...,Sold 02/07/2024,489212.0,5108 N Capitol St NW,20011.0,Washington,DC,TOWNHOUSE,3449.0,465000.0,RECENTLY_SOLD
6203,RecentChange,True,Sold,4.0,4.0,2875.0,RecentChange,False,False,True,...,Sold 02/07/2024,496388.0,3110 10th St NE,20017.0,Washington,DC,SINGLE_FAMILY,4749.0,1020000.0,RECENTLY_SOLD
6204,Non Owner Occupied,False,Sold,4.0,2.5,1260.0,Unknown Listed By,False,False,False,...,Sold 02/07/2024,508533.0,331 16th St NE,20002.0,Washington,DC,SINGLE_FAMILY,3994.0,550000.0,RECENTLY_SOLD
6205,RecentChange,True,Sold,3.0,2.0,1264.0,Unknown Listed By,False,False,True,...,Sold 02/07/2024,513167.0,5218 Hayes St NE,20019.0,Washington,DC,SINGLE_FAMILY,2949.0,370000.0,RECENTLY_SOLD

In [99]:
df.drop(columns=["variableData.type"],inplace=True)

In [100]:
df.dtypes.value_counts()

object     11
float64     9
bool        2
Name: count, dtype: int64

In [101]:
df

,marketingStatusSimplifiedCd,hasImage,statusText,beds,baths,area,sgapt,has3DModel,hasVideo,hasAdditionalAttributions,...,variableData.text,hdpData.homeInfo.zpid,hdpData.homeInfo.streetAddress,hdpData.homeInfo.zipcode,hdpData.homeInfo.city,hdpData.homeInfo.state,hdpData.homeInfo.homeType,hdpData.homeInfo.rentZestimate,price,hdpData.homeInfo.homeStatusForHDP
0,Non Owner Occupied,True,Sold,3.0,2.0,1224.0,Unknown Listed By,False,False,True,...,Sold 03/05/2024,59141778.0,9 Robken Rd,2131.0,Roslindale,MA,SINGLE_FAMILY,3999.0,819500.0,NaN
1,RecentChange,True,Sold,1.0,1.0,723.0,Unknown Listed By,False,False,True,...,Sold 03/05/2024,59172422.0,130 Appleton St APT 2A,2116.0,Boston,MA,CONDO,3634.0,880000.0,RECENTLY_SOLD
2,RecentChange,True,Sold,6.0,3.0,3396.0,Unknown Listed By,False,False,True,...,Sold 03/04/2024,59109603.0,64 Bakersfield St,2125.0,Dorchester,MA,MULTI_FAMILY,6000.0,1250000.0,RECENTLY_SOLD
3,RecentChange,True,Sold,4.0,3.0,2400.0,Unknown Listed By,False,False,True,...,Sold 03/04/2024,59110140.0,123 Norwell St,2121.0,Dorchester,MA,MULTI_FAMILY,4964.0,805000.0,RECENTLY_SOLD
4,RecentChange,True,Sold,9.0,3.0,4107.0,RecentChange,False,False,True,...,Sold 03/04/2024,59111749.0,8 Fowler St,2121.0,Dorchester,MA,MULTI_FAMILY,8970.0,650000.0,RECENTLY_SOLD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6201,RecentChange,True,Sold,5.0,4.0,2366.0,Unknown Listed By,False,False,True,...,Sold 02/07/2024,486407.0,308 Quackenbos St NW,20011.0,Washington,DC,SINGLE_FAMILY,4999.0,1125000.0,RECENTLY_SOLD
6202,RecentChange,True,Sold,3.0,3.0,1802.0,Unknown Listed By,False,False,True,...,Sold 02/07/2024,489212.0,5108 N Capitol St NW,20011.0,Washington,DC,TOWNHOUSE,3449.0,465000.0,RECENTLY_SOLD
6203,RecentChange,True,Sold,4.0,4.0,2875.0,RecentChange,False,False,True,...,Sold 02/07/2024,496388.0,3110 10th St NE,20017.0,Washington,DC,SINGLE_FAMILY,4749.0,1020000.0,RECENTLY_SOLD
6204,Non Owner Occupied,False,Sold,4.0,2.5,1260.0,Unknown Listed By,False,False,False,...,Sold 02/07/2024,508533.0,331 16th St NE,20002.0,Washington,DC,SINGLE_FAMILY,3994.0,550000.0,RECENTLY_SOLD
6205,RecentChange,True,Sold,3.0,2.0,1264.0,Unknown Listed By,False,False,True,...,Sold 02/07/2024,513167.0,5218 Hayes St NE,20019.0,Washington,DC,SINGLE_FAMILY,2949.0,370000.0,RECENTLY_SOLD

In [102]:
def removeColPrefix(colName):
    prefixes = ["hdpData.homeInfo.", "latLong."]
    for prefix in prefixes:
        if colName.startswith(prefix):
            colName = colName.replace(prefix, "")
            break  # Exit loop once a prefix is found and removed
    return colName


df.rename(columns={key:removeColPrefix(key) for key in df.columns },inplace=True)

df

,marketingStatusSimplifiedCd,hasImage,statusText,beds,baths,area,sgapt,has3DModel,hasVideo,hasAdditionalAttributions,...,variableData.text,zpid,streetAddress,zipcode,city,state,homeType,rentZestimate,price,homeStatusForHDP
0,Non Owner Occupied,True,Sold,3.0,2.0,1224.0,Unknown Listed By,False,False,True,...,Sold 03/05/2024,59141778.0,9 Robken Rd,2131.0,Roslindale,MA,SINGLE_FAMILY,3999.0,819500.0,NaN
1,RecentChange,True,Sold,1.0,1.0,723.0,Unknown Listed By,False,False,True,...,Sold 03/05/2024,59172422.0,130 Appleton St APT 2A,2116.0,Boston,MA,CONDO,3634.0,880000.0,RECENTLY_SOLD
2,RecentChange,True,Sold,6.0,3.0,3396.0,Unknown Listed By,False,False,True,...,Sold 03/04/2024,59109603.0,64 Bakersfield St,2125.0,Dorchester,MA,MULTI_FAMILY,6000.0,1250000.0,RECENTLY_SOLD
3,RecentChange,True,Sold,4.0,3.0,2400.0,Unknown Listed By,False,False,True,...,Sold 03/04/2024,59110140.0,123 Norwell St,2121.0,Dorchester,MA,MULTI_FAMILY,4964.0,805000.0,RECENTLY_SOLD
4,RecentChange,True,Sold,9.0,3.0,4107.0,RecentChange,False,False,True,...,Sold 03/04/2024,59111749.0,8 Fowler St,2121.0,Dorchester,MA,MULTI_FAMILY,8970.0,650000.0,RECENTLY_SOLD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6201,RecentChange,True,Sold,5.0,4.0,2366.0,Unknown Listed By,False,False,True,...,Sold 02/07/2024,486407.0,308 Quackenbos St NW,20011.0,Washington,DC,SINGLE_FAMILY,4999.0,1125000.0,RECENTLY_SOLD
6202,RecentChange,True,Sold,3.0,3.0,1802.0,Unknown Listed By,False,False,True,...,Sold 02/07/2024,489212.0,5108 N Capitol St NW,20011.0,Washington,DC,TOWNHOUSE,3449.0,465000.0,RECENTLY_SOLD
6203,RecentChange,True,Sold,4.0,4.0,2875.0,RecentChange,False,False,True,...,Sold 02/07/2024,496388.0,3110 10th St NE,20017.0,Washington,DC,SINGLE_FAMILY,4749.0,1020000.0,RECENTLY_SOLD
6204,Non Owner Occupied,False,Sold,4.0,2.5,1260.0,Unknown Listed By,False,False,False,...,Sold 02/07/2024,508533.0,331 16th St NE,20002.0,Washington,DC,SINGLE_FAMILY,3994.0,550000.0,RECENTLY_SOLD
6205,RecentChange,True,Sold,3.0,2.0,1264.0,Unknown Listed By,False,False,True,...,Sold 02/07/2024,513167.0,5218 Hayes St NE,20019.0,Washington,DC,SINGLE_FAMILY,2949.0,370000.0,RECENTLY_SOLD

In [103]:
df.drop(columns=["zpid"],inplace=True)

In [104]:
df.columns

Index(['marketingStatusSimplifiedCd', 'hasImage', 'statusText', 'beds',
       'baths', 'area', 'sgapt', 'has3DModel', 'hasVideo',
       'hasAdditionalAttributions', 'latitude', 'longitude',
       'variableData.text', 'streetAddress', 'zipcode', 'city', 'state',
       'homeType', 'rentZestimate', 'price', 'homeStatusForHDP'],
      dtype='object')

In [105]:
df.drop(columns=["variableData.text"],inplace=True)

,marketingStatusSimplifiedCd,hasImage,statusText,beds,baths,area,sgapt,has3DModel,hasVideo,hasAdditionalAttributions,latitude,longitude,streetAddress,zipcode,city,state,homeType,rentZestimate,price,homeStatusForHDP
0,Non Owner Occupied,True,Sold,3.0,2.0,1224.0,Unknown Listed By,False,False,True,42.293304,-71.133570,9 Robken Rd,2131.0,Roslindale,MA,SINGLE_FAMILY,3999.0,819500.0,NaN
1,RecentChange,True,Sold,1.0,1.0,723.0,Unknown Listed By,False,False,True,42.344826,-71.074990,130 Appleton St APT 2A,2116.0,Boston,MA,CONDO,3634.0,880000.0,RECENTLY_SOLD
2,RecentChange,True,Sold,6.0,3.0,3396.0,Unknown Listed By,False,False,True,42.315850,-71.061130,64 Bakersfield St,2125.0,Dorchester,MA,MULTI_FAMILY,6000.0,1250000.0,RECENTLY_SOLD
3,RecentChange,True,Sold,4.0,3.0,2400.0,Unknown Listed By,False,False,True,42.298183,-71.078870,123 Norwell St,2121.0,Dorchester,MA,MULTI_FAMILY,4964.0,805000.0,RECENTLY_SOLD
4,RecentChange,True,Sold,9.0,3.0,4107.0,RecentChange,False,False,True,42.300050,-71.083694,8 Fowler St,2121.0,Dorchester,MA,MULTI_FAMILY,8970.0,650000.0,RECENTLY_SOLD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6201,RecentChange,True,Sold,5.0,4.0,2366.0,Unknown Listed By,False,False,True,38.963560,-77.016990,308 Quackenbos St NW,20011.0,Washington,DC,SINGLE_FAMILY,4999.0,1125000.0,RECENTLY_SOLD
6202,RecentChange,True,Sold,3.0,3.0,1802.0,Unknown Listed By,False,False,True,38.952750,-77.009360,5108 N Capitol St NW,20011.0,Washington,DC,TOWNHOUSE,3449.0,465000.0,RECENTLY_SOLD
6203,RecentChange,True,Sold,4.0,4.0,2875.0,RecentChange,False,False,True,38.928920,-76.992680,3110 10th St NE,20017.0,Washington,DC,SINGLE_FAMILY,4749.0,1020000.0,RECENTLY_SOLD
6204,Non Owner Occupied,False,Sold,4.0,2.5,1260.0,Unknown Listed By,False,False,False,38.894318,-76.981830,331 16th St NE,20002.0,Washington,DC,SINGLE_FAMILY,3994.0,550000.0,RECENTLY_SOLD
6205,RecentChange,True,Sold,3.0,2.0,1264.0,Unknown Listed By,False,False,True,38.899930,-76.925570,5218 Hayes St NE,20019.0,Washington,DC,SINGLE_FAMILY,2949.0,370000.0,RECENTLY_SOLD

In [108]:
df.to_csv("vijay_cleaned.csv")